# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

zidm_bvs <- function(iterations, thin, z, x, x_theta, beta_gamma, cc, temp_uu, eta, eta_accept, eta_index, omega, beta_theta, zeta, varphi, sigma2_beta_gamma, a_varphi, b_varphi, a_zeta, b_zeta, sigma2_beta_theta) {
    .Call(`_ZIDM_zidm_bvs`, iterations, thin, z, x, x_theta, beta_gamma, cc, temp_uu, eta, eta_accept, eta_index, omega, beta_theta, zeta, varphi, sigma2_beta_gamma, a_varphi, b_varphi, a_zeta, b_zeta, sigma2_beta_theta)
}

zidm <- function(iterations, thin, z, x, x_theta, beta_gamma, cc, temp_uu, eta, eta_accept, eta_index, omega, beta_theta, zeta, varphi, sigma2_beta_gamma, sigma2_beta_theta) {
    .Call(`_ZIDM_zidm`, iterations, thin, z, x, x_theta, beta_gamma, cc, temp_uu, eta, eta_accept, eta_index, omega, beta_theta, zeta, varphi, sigma2_beta_gamma, sigma2_beta_theta)
}

dm_bvs <- function(iterations, thin, z, x, beta_gamma, cc, temp_uu, eta, eta_index, varphi, sigma2_beta_gamma, a_varphi, b_varphi) {
    .Call(`_ZIDM_dm_bvs`, iterations, thin, z, x, beta_gamma, cc, temp_uu, eta, eta_index, varphi, sigma2_beta_gamma, a_varphi, b_varphi)
}

dm <- function(iterations, thin, z, x, beta_gamma, cc, temp_uu, eta, eta_index, varphi, sigma2_beta_gamma) {
    .Call(`_ZIDM_dm`, iterations, thin, z, x, beta_gamma, cc, temp_uu, eta, eta_index, varphi, sigma2_beta_gamma)
}

tuyl <- function(iterations, z) {
    .Call(`_ZIDM_tuyl`, iterations, z)
}

tuyl_meaner <- function(z) {
    .Call(`_ZIDM_tuyl_meaner`, z)
}

